version: '3.8'
services:
  api:
    build: .
    container_name: kib-tmdb-service
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: mongo:5
    container_name: mongo-db
    ports:
      - '27017:27017'

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - '6379:6379'
